########################################基本配置########################################
server:
  port: 1112

spring:
  application:
    name: user
  profiles:
    active: dev



########################################数据库配置########################################
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/study-user?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456