########################################基本配置########################################
server:
  port: 80

spring:
  application:
    name: wx



########################################wx配置########################################
wx:
  mp:
    app-id: wx5553e8da52fcd86d
    secret: bc2be8260fcef32b7a11b2d1c5a99c1f
    token: 123456



########################################自定义########################################
web-study:
  zookeeper:
    configuration-properties:
    serverUrl: 127.0.0.1:10000
    sessionTimeOut: 50000