########################################服务注册与发现配置########################################
server:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



########################################基本配置########################################
  port: 1110

spring:
  application:
    name: gateway



########################################服务注册与发现配置########################################
  cloud:
    gateway:
      routes:
        #####car模块#####
        - id: car
          uri: lb://car
          predicates:
            - Path=/car/**
        #####user模块#####
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        #####wx模块#####
        - id: wx
          uri: lb://wx
          predicates:
            - Path=/wx/**
        #####user模块#####
        - id: user2
          uri: lb://user2
          predicates:
            - Path=/user2/**
        #####pay模块#####
        - id: pay
          uri: lb://pay
          predicates:
            - Path=/pay/**
        #####system模块#####
        - id: system模块
          uri: lb://system
          predicates:
            - Path=/system/**