########################################服务注册与发现配置########################################
server:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



########################################基本配置########################################
  port: 1110

spring:
  application:
    name: gateway