########################################服务注册与发现配置########################################
server:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



########################################基本配置########################################
  port: 1110

spring:
  application:
    name: gateway



########################################服务注册与发现配置########################################
  cloud:
    gateway:
      routes:
        #####car模块#####
        - id: car
          uri: lb://car
          predicates:
            - Path=/car/**
        #####car模块#####
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**