########################################nacos配置########################################
server:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



########################################mybatis配置########################################
mybatis-plus:
  configuration:
    ###这是什么？日志路径如何配置？
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:/mapper/*Mapper.xml
    lazyLoadingEnabled: true
    aggressiveLazyLoad: true
    cache-enabled: true



########################################pagehelper配置########################################
pagehelper:
  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count




########################################redis配置########################################
spring:
  redis:
    database: 0 #redis数据库索引
#    host: localhost
    port: 6379
#    password: null
    timeout: 10000
    connectTimeout: 10000



########################################zookeeper配置########################################
  zookeeper:
    address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    timeout: 10000000



########################################kafka配置########################################
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: -1
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: latest
      max-poll-records: 500
      fetch-max-wait: 500
      fetch-min-size: 1
      heartbeat-interval: 3000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer