########################################服务注册与发现配置########################################
server:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



########################################mybatis配置########################################
mybatis-plus:
  configuration:
    ###这是什么？日志路径如何配置？
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:/mapper/*Mapper.xml
    lazyLoadingEnabled: true
    aggressiveLazyLoad: true
    cache-enabled: true



########################################pagehelper配置########################################
pagehelper:
  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count



