########################################服务注册与发现配置########################################
server:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848



########################################mybatis配置########################################
mybatis-plus:
  configuration:
    ###这是什么？日志路径如何配置？
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:/mapper/*Mapper.xml
    lazyLoadingEnabled: true
    aggressiveLazyLoad: true
    cache-enabled: true



########################################pagehelper配置########################################
pagehelper:
  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count



########################################redis配置########################################
spring:
  redis:
    database: 0 #redis数据库索引
    host: localhost
    port: 6379
#    password: null
    timeout: 10000
    connectTimeout: 10000



########################################zookeeper配置########################################
  zookeeper:
    address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
    timeout: 4000
