server:
  port: 1111

spring:
  application:
    name: school

  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://127.0.0.1:3306/school?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456

mybatis-plus:
  configuration:
    ###这是什么？日志路径如何配置？
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:/mapper/*Mapper.xml
    lazyLoadingEnabled: true
    aggressiveLazyLoad: true

#pagehelper配置
pagehelper:
  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count



########################################自定义########################################
web-study:
  zookeeper:
    configuration-properties:
    serverUrl: 127.0.0.1:10000
    sessionTimeOut: 50000